"use client"

import { useRef, useState } from "react"
import { Cloud, Download, HardDrive, KeyRound, Moon, Save, ShieldCheck, Sun, Upload } from "lucide-react"
import { useTheme } from "next-themes"
import { toast } from "sonner"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Switch } from "@/components/ui/switch"
import { db } from "@/database/db"
import { downloadBlob } from "@/lib/tailor-utils"
import { decryptBackup, encryptBackup, restoreBackup, saveBackupRecord } from "@/services/backup"
import type { AppSettings } from "@/types/tailor"

export function BackupView({ settings }: { settings: AppSettings }) {
  const inputRef = useRef<HTMLInputElement>(null); const [secret, setSecret] = useState(settings.backupSecret ?? ""); const [busy, setBusy] = useState(false)
  async function backup() { if (secret.length < 6) return toast.error("أدخل رمزاً احتياطياً من 6 أحرف على الأقل"); setBusy(true); try { const payload = await encryptBackup(secret); await saveBackupRecord(payload); await db.settings.update("main", { backupSecret: secret }); downloadBlob(new Blob([payload], { type: "application/json" }), `khayati-${new Date().toISOString().slice(0, 10)}.tailor`); toast.success("تم إنشاء نسخة مشفرة") } catch { toast.error("تعذر إنشاء النسخة") } finally { setBusy(false) } }
  async function restore(file?: File) { if (!file || secret.length < 6) return toast.error("أدخل الرمز المستخدم لتشفير النسخة"); const mode = window.confirm("موافق: استبدال البيانات الحالية. إلغاء: دمج البيانات.") ? "replace" : "merge"; setBusy(true); try { if (mode === "replace") { const safety = await encryptBackup(secret); await saveBackupRecord(safety, "safety") } const data = await decryptBackup(await file.text(), secret); await restoreBackup(data.operations, data.settings, mode); toast.success("تمت الاستعادة بنجاح") } catch { toast.error("الملف أو الرمز الاحتياطي غير صحيح") } finally { setBusy(false); if (inputRef.current) inputRef.current.value = "" } }
  return <div className="flex flex-col gap-5"><div><p className="eyebrow">حماية محلية مشفرة</p><h1 className="text-3xl font-bold">النسخ الاحتياطي</h1><p className="mt-1 text-sm text-muted-foreground">تشفير AES‑GCM قبل الحفظ أو التنزيل.</p></div><Alert><ShieldCheck /><AlertTitle>احتفظ بالرمز في مكان آمن</AlertTitle><AlertDescription>لا يمكن قراءة النسخة على جهاز جديد دون الرمز الاحتياطي.</AlertDescription></Alert><Card><CardHeader><CardTitle>الرمز الاحتياطي</CardTitle><CardDescription>ستحتاجه فقط عند الاستعادة على جهاز آخر.</CardDescription></CardHeader><CardContent><div className="flex flex-col gap-3 sm:flex-row"><Input type="password" value={secret} onChange={(event) => setSecret(event.target.value)} placeholder="6 أحرف أو أكثر" /><Button onClick={backup} disabled={busy}><Download data-icon="inline-start" />نسخة مشفرة الآن</Button></div></CardContent></Card><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><HardDrive /><CardTitle>استعادة آمنة</CardTitle><CardDescription>يمكن الدمج أو الاستبدال؛ ويُنشأ حفظ أمان قبل الاستبدال.</CardDescription></CardHeader><CardContent><input ref={inputRef} type="file" accept=".tailor,application/json" className="sr-only" onChange={(event) => restore(event.target.files?.[0])} /><Button variant="outline" onClick={() => inputRef.current?.click()} disabled={busy}><Upload data-icon="inline-start" />اختيار نسخة</Button></CardContent></Card><Card><CardHeader><Cloud /><CardTitle>Google Drive</CardTitle><CardDescription>رفع تلقائي عند توفر OAuth Client ID واتصال إنترنت.</CardDescription></CardHeader><CardContent><p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">{settings.driveClientId ? "Client ID محفوظ. التفويض يتم من هذا الجهاز عند تفعيل الربط." : "أضف Client ID في الإعدادات. النسخ المحلية لا تتأثر."}</p></CardContent></Card></div>{settings.lastBackupAt && <p className="text-sm text-muted-foreground">آخر نسخة ناجحة: {new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(settings.lastBackupAt))}</p>}</div>
}

export function SettingsView({ settings }: { settings: AppSettings }) {
  const { setTheme } = useTheme(); const [form, setForm] = useState(settings)
  async function save() { await db.settings.put(form); setTheme(form.theme); toast.success("تم حفظ الإعدادات") }
  return <div className="flex max-w-3xl flex-col gap-5"><div><p className="eyebrow">تخصيص خياطتي</p><h1 className="text-3xl font-bold">الإعدادات</h1></div><Card><CardHeader><CardTitle>بيانات المحل</CardTitle><CardDescription>تظهر في التقارير والنسخ المطبوعة.</CardDescription></CardHeader><CardContent><FieldGroup><Field><FieldLabel htmlFor="shopName">اسم المحل</FieldLabel><Input id="shopName" value={form.shopName} onChange={(event) => setForm({ ...form, shopName: event.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="ownerName">اسم المالك</FieldLabel><Input id="ownerName" value={form.ownerName} onChange={(event) => setForm({ ...form, ownerName: event.target.value })} /></Field><Field><FieldLabel htmlFor="phone">الجوال</FieldLabel><Input id="phone" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></Field></div><Field><FieldLabel>العملة الافتراضية</FieldLabel><select className="h-10 rounded-lg border bg-background px-3" value={form.defaultCurrency} onChange={(event) => setForm({ ...form, defaultCurrency: event.target.value as "SAR" | "YER" })}><option value="SAR">ريال سعودي</option><option value="YER">ريال يمني</option></select></Field></FieldGroup></CardContent></Card><Card><CardHeader><CardTitle>المظهر والنسخ</CardTitle></CardHeader><CardContent><FieldGroup><Field orientation="horizontal"><FieldLabel>الوضع الليلي</FieldLabel><Button variant="outline" onClick={() => { const theme = form.theme === "dark" ? "light" : "dark"; setForm({ ...form, theme }); setTheme(theme) }}>{form.theme === "dark" ? <Sun /> : <Moon />}{form.theme === "dark" ? "نهاري" : "ليلي"}</Button></Field><Field orientation="horizontal"><div><FieldLabel>النسخ التلقائي</FieldLabel><FieldDescription>عند فتح التطبيق وفق الجدول المحدد.</FieldDescription></div><Switch checked={form.autoBackup} onCheckedChange={(checked) => setForm({ ...form, autoBackup: checked })} /></Field><Field><FieldLabel>الجدول</FieldLabel><select className="h-10 rounded-lg border bg-background px-3" value={form.backupSchedule} onChange={(event) => setForm({ ...form, backupSchedule: event.target.value as AppSettings["backupSchedule"] })}><option value="daily">يومي</option><option value="weekly">أسبوعي</option><option value="manual">يدوي</option></select></Field><Field><FieldLabel htmlFor="clientId">Google OAuth Client ID</FieldLabel><Input id="clientId" dir="ltr" value={form.driveClientId} onChange={(event) => setForm({ ...form, driveClientId: event.target.value })} /><FieldDescription>اختياري ولا يعطل النسخ المحلية.</FieldDescription></Field><Button onClick={save}><Save data-icon="inline-start" />حفظ الإعدادات</Button></FieldGroup></CardContent></Card><div className="flex items-center gap-2 text-sm text-muted-foreground"><KeyRound />لا تتم مزامنة الرمز الاحتياطي مع أي خادم.</div></div>
}
