"use client"

import { useRef, useState } from "react"
import { useLiveQuery } from "dexie-react-hooks"
import { Archive, CheckCircle2, Download, HardDrive, LoaderCircle, Moon, Save, Share2, ShieldCheck, Sun, Upload, XCircle } from "lucide-react"
import { useTheme } from "next-themes"
import { toast } from "sonner"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Switch } from "@/components/ui/switch"
import { db } from "@/database/db"
import { downloadBlob } from "@/lib/tailor-utils"
import { decryptBackup, encryptBackup, restoreBackup, saveBackupFailure, saveBackupRecord } from "@/services/backup"
import type { AppSettings } from "@/types/tailor"

const dateTime = new Intl.DateTimeFormat("ar-SA", { dateStyle: "medium", timeStyle: "short" })
const sourceLabels = { local: "محلية", safety: "نسخة أمان", drive: "قديمة" }
function formatSize(size: number) { return size ? `${(size / 1024).toLocaleString("ar-SA", { maximumFractionDigits: 1 })} ك.ب` : "—" }

export function BackupView({ settings }: { settings: AppSettings }) {
  const inputRef = useRef<HTMLInputElement>(null)
  const [secret, setSecret] = useState(settings.backupSecret ?? "")
  const [busy, setBusy] = useState<"backup" | "share" | "restore" | null>(null)
  const backups = useLiveQuery(() => db.backups.orderBy("createdAt").reverse().toArray(), [], [])
  async function createPayload(source: "local" | "safety" = "local") { const payload = await encryptBackup(secret); await saveBackupRecord(payload, source); await db.settings.update("main", { backupSecret: secret }); return payload }
  async function backup() { if (secret.length < 6) return toast.error("أدخل رمزاً احتياطياً من 6 أحرف على الأقل"); if (busy) return; setBusy("backup"); try { const payload = await createPayload(); downloadBlob(new Blob([payload], { type: "application/json" }), `khayati-${new Date().toISOString().slice(0, 10)}.tailor`); toast.success("تم إنشاء نسخة مشفرة") } catch (error) { await saveBackupFailure(error instanceof Error ? error.message : "backup-failed"); toast.error("تعذر إنشاء النسخة") } finally { setBusy(null) } }
  async function share() { if (secret.length < 6) return toast.error("أدخل رمزاً احتياطياً من 6 أحرف على الأقل"); if (busy) return; setBusy("share"); try { const payload = await createPayload(); const file = new File([payload], `khayati-${new Date().toISOString().slice(0, 10)}.tailor`, { type: "application/json" }); if (navigator.share && navigator.canShare?.({ files: [file] })) { await navigator.share({ title: "نسخة خياطتي المشفرة", files: [file] }); toast.success("تمت مشاركة النسخة") } else { downloadBlob(file, file.name); toast.success("جهازك لا يدعم المشاركة؛ تم تنزيل النسخة بأمان") } } catch (error) { if (error instanceof DOMException && error.name === "AbortError") return; await saveBackupFailure(error instanceof Error ? error.message : "share-failed"); toast.error("تعذرت مشاركة النسخة") } finally { setBusy(null) } }
  async function restore(file?: File) { if (!file || secret.length < 6) return toast.error("أدخل الرمز المستخدم لتشفير النسخة"); if (busy) return; const mode = window.confirm("موافق: استبدال البيانات الحالية. إلغاء: دمج البيانات.") ? "replace" : "merge"; setBusy("restore"); try { if (mode === "replace") await createPayload("safety"); const data = await decryptBackup(await file.text(), secret); await restoreBackup(data.operations, data.settings, mode); toast.success("تمت الاستعادة بنجاح") } catch { toast.error("الملف أو الرمز الاحتياطي غير صحيح") } finally { setBusy(null); if (inputRef.current) inputRef.current.value = "" } }
  return <div className="flex flex-col gap-5">
    <div><p className="eyebrow">حماية محلية مشفرة</p><h1 className="text-3xl font-bold">مركز البيانات</h1><p className="mt-1 text-sm text-muted-foreground">أنشئ، شارك واستعد نسخ AES‑GCM الآمنة.</p></div>
    <Alert><ShieldCheck /><AlertTitle>احتفظ بالرمز في مكان آمن</AlertTitle><AlertDescription>لا يمكن قراءة النسخة على جهاز جديد دون الرمز الاحتياطي.</AlertDescription></Alert>
    <Card><CardHeader><CardTitle>الرمز الاحتياطي</CardTitle><CardDescription>ستحتاجه فقط عند الاستعادة على جهاز آخر.</CardDescription></CardHeader><CardContent><div className="flex flex-col gap-3 sm:flex-row"><Input type="password" value={secret} onChange={(event) => setSecret(event.target.value)} placeholder="6 أحرف أو أكثر" /><Button onClick={backup} disabled={!!busy}>{busy === "backup" ? <LoaderCircle className="animate-spin" /> : <Download />}نسخة مشفرة</Button><Button variant="outline" onClick={share} disabled={!!busy}>{busy === "share" ? <LoaderCircle className="animate-spin" /> : <Share2 />}مشاركة آمنة</Button></div></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><HardDrive /><CardTitle>استعادة آمنة</CardTitle><CardDescription>يمكن الدمج أو الاستبدال؛ ويُنشأ حفظ أمان قبل الاستبدال.</CardDescription></CardHeader><CardContent><input ref={inputRef} type="file" accept=".tailor,application/json" className="sr-only" onChange={(event) => restore(event.target.files?.[0])} /><Button variant="outline" onClick={() => inputRef.current?.click()} disabled={!!busy}>{busy === "restore" ? <LoaderCircle className="animate-spin" /> : <Upload />}اختيار نسخة</Button></CardContent></Card><Card><CardHeader><Archive /><CardTitle>حالة قاعدة البيانات</CardTitle><CardDescription>سجل محلي لعمليات النسخ الحالية والسابقة.</CardDescription></CardHeader><CardContent className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-muted p-3"><p className="text-xs text-muted-foreground">إجمالي النسخ</p><strong className="text-2xl">{backups.length}</strong></div><div className="rounded-xl bg-muted p-3"><p className="text-xs text-muted-foreground">الحالة</p><strong>{backups[0]?.status === "failed" ? "تحتاج مراجعة" : "سليمة"}</strong></div></CardContent></Card></div>
    <Card><CardHeader><CardTitle>سجل النسخ</CardTitle><CardDescription>آخر محاولات النسخ المشفرة على هذا الجهاز.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2">{backups.length === 0 ? <p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">لا توجد نسخ مسجلة بعد.</p> : backups.slice(0, 8).map((record) => <div key={record.id} className="flex flex-col justify-between gap-2 rounded-xl border p-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3">{record.status === "success" ? <CheckCircle2 className="text-primary" /> : <XCircle className="text-destructive" />}<div><p className="text-sm font-medium">{sourceLabels[record.source]}</p><p className="text-xs text-muted-foreground">{dateTime.format(new Date(record.createdAt))}</p></div></div><div className="flex items-center gap-2"><Badge variant={record.status === "success" ? "secondary" : "destructive"}>{record.status === "success" ? "ناجحة" : "فشلت"}</Badge><span className="text-xs text-muted-foreground">{formatSize(record.size)}</span></div></div>)}</CardContent></Card>
  </div>
}

export function SettingsView({ settings }: { settings: AppSettings }) {
  const { setTheme } = useTheme(); const [form, setForm] = useState(settings); const [saving, setSaving] = useState(false)
  async function save() { if (saving) return; setSaving(true); try { await db.settings.put(form); setTheme(form.theme); toast.success("تم حفظ الإعدادات") } catch { toast.error("تعذر حفظ الإعدادات") } finally { setSaving(false) } }
  return <div className="flex max-w-3xl flex-col gap-5"><div><p className="eyebrow">تخصيص خياطتي</p><h1 className="text-3xl font-bold">الإعدادات</h1></div><Card><CardHeader><CardTitle>بيانات المحل</CardTitle><CardDescription>تظهر في التقارير والنسخ المطبوعة.</CardDescription></CardHeader><CardContent><FieldGroup><Field><FieldLabel htmlFor="shopName">اسم المحل</FieldLabel><Input id="shopName" value={form.shopName} onChange={(event) => setForm({ ...form, shopName: event.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel htmlFor="ownerName">اسم المالك</FieldLabel><Input id="ownerName" value={form.ownerName} onChange={(event) => setForm({ ...form, ownerName: event.target.value })} /></Field><Field><FieldLabel htmlFor="phone">الجوال</FieldLabel><Input id="phone" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></Field></div><Field><FieldLabel>العملة الافتراضية</FieldLabel><select className="h-10 rounded-lg border bg-background px-3" value={form.defaultCurrency} onChange={(event) => setForm({ ...form, defaultCurrency: event.target.value as "SAR" | "YER" })}><option value="SAR">ريال سعودي</option><option value="YER">ريال يمني</option></select></Field></FieldGroup></CardContent></Card><Card><CardHeader><CardTitle>المظهر والنسخ</CardTitle></CardHeader><CardContent><FieldGroup><Field orientation="horizontal"><FieldLabel>الوضع الليلي</FieldLabel><Button variant="outline" onClick={() => { const theme = form.theme === "dark" ? "light" : "dark"; setForm({ ...form, theme }); setTheme(theme) }}>{form.theme === "dark" ? <Sun /> : <Moon />}{form.theme === "dark" ? "نهاري" : "ليلي"}</Button></Field><Field orientation="horizontal"><div><FieldLabel>النسخ التلقائي</FieldLabel><FieldDescription>عند فتح التطبيق وفق الجدول المحدد.</FieldDescription></div><Switch checked={form.autoBackup} onCheckedChange={(checked) => setForm({ ...form, autoBackup: checked })} /></Field><Field><FieldLabel>الجدول</FieldLabel><select className="h-10 rounded-lg border bg-background px-3" value={form.backupSchedule} onChange={(event) => setForm({ ...form, backupSchedule: event.target.value as AppSettings["backupSchedule"] })}><option value="daily">يومي</option><option value="weekly">أسبوعي</option><option value="manual">يدوي</option></select></Field></FieldGroup></CardContent></Card><Button className="w-fit" onClick={save} disabled={saving}>{saving ? <LoaderCircle className="animate-spin" /> : <Save />}حفظ الإعدادات</Button></div>
}
