"use client"

import { useMemo, useState } from "react"
import { Bar, BarChart, CartesianGrid, XAxis } from "recharts"
import { Banknote, CircleDollarSign, FileSpreadsheet, LoaderCircle, PackageCheck, WalletCards } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { ChartContainer, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart"
import { Input } from "@/components/ui/input"
import { formatMoney, operationRemaining, operationTotal, totalsByCurrency } from "@/lib/tailor-utils"
import type { TailorOperation } from "@/types/tailor"

const chartConfig = { total: { label: "الدخل", color: "var(--chart-1)" }, paid: { label: "المسحوب", color: "var(--chart-2)" } } satisfies ChartConfig
const icons = [CircleDollarSign, Banknote, WalletCards, PackageCheck]
const valueClasses = ["text-chart-1", "text-destructive", "text-primary", "text-chart-2"]

export function ReportsView({ operations }: { operations: TailorOperation[] }) {
  const [month, setMonth] = useState(() => new Date().toISOString().slice(0, 7)); const [exporting, setExporting] = useState(false)
  const filtered = useMemo(() => operations.filter((operation) => operation.date.startsWith(month)), [month, operations]); const totals = totalsByCurrency(filtered)
  const chartData = useMemo(() => Object.values(filtered.reduce<Record<string, { day: string; total: number; paid: number }>>((map, operation) => { const day = operation.date.slice(8, 10); const current = map[day] ?? { day, total: 0, paid: 0 }; current.total += operationTotal(operation); current.paid += operation.paid; map[day] = current; return map }, {})).sort((a, b) => a.day.localeCompare(b.day)), [filtered])
  const cards = [{ label: "إجمالي الأجور", sar: totals.SAR.total, yer: totals.YER.total }, { label: "المسحوب", sar: totals.SAR.paid, yer: totals.YER.paid }, { label: "المتبقي", sar: totals.SAR.remaining, yer: totals.YER.remaining }, { label: "القطع", pieces: filtered.reduce((sum, item) => sum + item.quantity, 0), operations: filtered.length }]
  async function exportExcel() { if (exporting || !filtered.length) return; setExporting(true); try { const XLSX = await import("xlsx"); const rows = filtered.map((item) => ({ التاريخ: item.date.slice(0, 10), القطعة: item.pieceType, العدد: item.quantity, العملة: item.currency, الإجمالي: operationTotal(item), المدفوع: item.paid, المتبقي: operationRemaining(item), العملاء: item.customers.map((customer) => customer.name).join("، ") })); const workbook = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(rows), "التقرير"); XLSX.writeFile(workbook, `تقرير-${month}.xlsx`); toast.success("تم تصدير التقرير") } catch { toast.error("تعذر تصدير التقرير") } finally { setExporting(false) } }
  return <div className="flex flex-col gap-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">أداء العمل</p><h1 className="text-3xl font-bold">التقارير الشهرية</h1></div><div className="flex gap-2"><Input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /><Button variant="outline" onClick={exportExcel} disabled={!filtered.length || exporting}>{exporting ? <LoaderCircle className="animate-spin" /> : <FileSpreadsheet />}Excel</Button></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map((item, index) => { const Icon = icons[index]; return <Card key={item.label} className="stat-card overflow-hidden"><CardHeader className="flex flex-row items-start justify-between gap-3 pb-3"><div><CardDescription className="font-medium">{item.label}</CardDescription><CardTitle className={`mt-3 min-h-8 text-2xl font-bold leading-8 tabular-nums ${valueClasses[index]}`}>{item.pieces !== undefined ? item.pieces.toLocaleString("ar-SA") : formatMoney(item.sar ?? 0, "SAR")}</CardTitle></div><span className="flex size-11 items-center justify-center rounded-xl bg-accent text-accent-foreground"><Icon /></span></CardHeader><CardContent><p className={`min-h-6 text-sm font-bold leading-6 tabular-nums ${valueClasses[index]}`}>{item.pieces !== undefined ? `${item.operations} عملية` : formatMoney(item.yer ?? 0, "YER")}</p></CardContent></Card> })}</div><Card><CardHeader><CardTitle>اتجاه الدخل</CardTitle><CardDescription>الإجمالي والمسحوب بحسب اليوم، مع عرض رقمي موحد للاتجاه فقط.</CardDescription></CardHeader><CardContent>{chartData.length ? <ChartContainer config={chartConfig} className="h-72 w-full"><BarChart accessibilityLayer data={chartData}><CartesianGrid vertical={false} /><XAxis dataKey="day" tickLine={false} axisLine={false} /><ChartTooltip content={<ChartTooltipContent />} /><Bar dataKey="total" fill="var(--color-total)" radius={6} /><Bar dataKey="paid" fill="var(--color-paid)" radius={6} /></BarChart></ChartContainer> : <p className="py-20 text-center text-sm text-muted-foreground">لا توجد بيانات لهذا الشهر.</p>}</CardContent></Card></div>
}
